<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxruv0c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxruv0c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXxruv0c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXxruv0c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXxruv0c\appDevDebugProjectContainer();
