version: '2'

services:
  php:
    build: ./docker/php
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./config/php.ini:/usr/local/etc/php/php.ini"
      - "./app:/var/www/project"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/project"
    depends_on:
      - php
    links:
      - php
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: project
    ports:
      - 3306:3306
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
       - mysql
      ports:
          - 8080:80
      links:
          - mysql
      environment:
          PMA_HOST: mysql
