<?php

namespace AppBundle\Repository;

/**
 * NextNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NextNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
