<?php

namespace AppBundle\Repository;

/**
 * NextMenuItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NextMenuItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
