<?php

namespace AppBundle\Repository;

/**
 * NextNewsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NextNewsCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
