<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkIfUserIsExist($referralId)
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.referralId = :referralId')
            ->setParameter('referralId', $referralId)
            ->andWhere('user.enabled = :enabled')
            ->setParameter('enabled',true)
            ->getQuery()
            ->execute();
    }
}
